services:
  server:
    build: .
    pull_policy: build
    restart: unless-stopped
    networks:
      - public-apps
    labels:
      traefik.enable: true
      traefik.http.routers.lenn-rocks.rule: Host(`lenn.rocks`) || Host(`www.lenn.rocks`) 
      traefik.http.services.lenn-rocks.loadbalancer.server.port: 80


networks:
  public-apps:
    external: true # hook into public network instead of creating our own
